### ISSUE TITLE
Full screen camera view

### ISSUE THREAD

**Issue by devlak2001** [alemart/martins-js#7] opened 2024-07-06 19:49 UTC
Hi, I tried tracking from your library and it's working perfectly. Is there a way to make the camera view always 100% width and 100% height of the screen? There is one more issue when the orientation of the browser changes, the camera view distorts, and I would like to keep it 100% width and 100% height even then.

Thank you in advance

**Comment by alemart** [comment] 2024-07-07 04:49
Hi,

It's possible to work in fullscreen and I'll add this feature to the API for ease of use.

For the time being, use `Element.requestFullscreen` on your `#ar-viewport`. I find no issues with changes in camera orientation.

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

**Comment by devlak2001** [comment] 2024-07-07 13:17
Hi, this is what I mean by changing orientation. https://github.com/alemart/martins-js/assets/68306415/fdd84b5d-c87d-4d14-b735-8e0ad0f2817b

**Comment by devlak2001** [comment] 2024-07-07 13:21
Also, it seems like Element.requestFullscreen isn't fully supported. So I would need to keep the camera view 100% and the height of the screen without using this API.

**Comment by alemart** [comment] 2024-07-08 02:44
Hi!

> Also, it seems like Element.requestFullscreen isn't fully supported. So I would like to keep the camera view 100% of the width and height of the screen without using this API.

`Element.requestFullscreen` works in all major browsers, except in Safari which in practice still requires the webkit prefix in a call. This is what I intend to do. Presently, Safari for iOS includes [only partial support](https://caniuse.com/mdn-api_element_requestfullscreen) for fullscreen, but [Apple is working on it](https://forums.developer.apple.com/forums/thread/133248).

Going fullscreen without using the Fullscreen API can be done with techniques that fall outside the scope of this project, like creating a WebView app or having users add the web app to their home screen, setting [vendor-specific meta tags](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html) and creating a [web app manifest](https://w3c.github.io/manifest/#display-modes).

Without going fullscreen, we can cover 100% of the page. Would this suffice? Presently, the video is scaled according to its aspect ratio.

> Hi, this is what I mean by changing orientation

Can you reproduce that with the demos of the website? I've been unable to reproduce it.

**Comment by alemart** [comment] 2024-07-16 01:58
Fullscreen support is [now available](https://alemart.github.io/martins-js/api/viewport/#requestfullscreen). In addition, it's now possible to make the viewport cover the entire page by changing its [style](https://alemart.github.io/martins-js/api/viewport/#style).

I'm closing this issue. Feel free to reach out again if you have further questions.

**Closed by alemart** 2024-07-16 01:58 UTC
